FROM golang:1.19 AS development
WORKDIR /go/src/github.com/escalopa/gobank
COPY gapi ./gapi
COPY grpc ./grpc
COPY db ./db
COPY token ./token
COPY util ./util
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/cespare/reflex@latest
CMD reflex -r '\.go$' -s -- sh -c 'go run gapi/cmd/main.go'

FROM golang:alpine AS build
WORKDIR /go/src/github.com/escalopa/gobank
COPY gapi ./gapi
COPY grpc ./grpc
COPY db ./db
COPY token ./token
COPY util ./util
COPY grpc ./grpc
COPY go.mod go.sum ./
RUN go build -o /go/bin/gapi gapi/cmd/main.go

FROM alpine:3.7 AS production
COPY --from=build /go/bin/gapi /go/bin/gapi
EXPOSE 8000
CMD ["/go/bin/gapi"]